/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 */

dependencyResolutionManagement {

    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

pluginManagement {
    val nebulaRelease: String by settings
    val nebulaMavenPublish: String by settings
    val nebulaContacts: String by settings
    val benNamesVersions: String by settings


    plugins {
        id("nebula.release") version nebulaRelease
        id("nebula.maven-nebula-publish") version nebulaMavenPublish
        id("nebula.contacts") version nebulaContacts
        id("com.github.ben-manes.versions") version benNamesVersions
    }

    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

rootProject.name = "beaver-publishing"
include("plugin")
