/*
 * This source file was generated by the Gradle 'init' task
 */
package org.beaver.publishing

import org.gradle.api.GradleException
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'org.beaver.greeting' plugin.
 */
class BeaverPublishingPluginTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("beaver.publishing")

        // Verify the result
        assertNotNull(project.tasks.findByName("publishNebulaPublicationToMavenLocal"))
    }
}
